name: Deploy with Automated Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run test:ci
      
    - name: Run security audit
      run: npm audit --audit-level moderate
      
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        vercel-args: '--prod'
        
    - name: Initialize Security Systems
      run: |
        sleep 30
        curl -X POST "${{ secrets.VERCEL_URL }}/api/deploy/complete" \
          -H "Authorization: Bearer ${{ secrets.DEPLOY_SECRET }}" \
          -H "Content-Type: application/json"
          
    - name: Verify Deployment
      run: |
        curl -f "${{ secrets.VERCEL_URL }}/api/health" || exit 1
        curl -f "${{ secrets.VERCEL_URL }}/api/security/dashboard" || exit 1
        
    - name: Security Monitoring Test
      run: |
        curl -f "${{ secrets.VERCEL_URL }}/api/security/monitor" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" || exit 1



